### PR TITLE
Speed up rendering of status page by placing images via css.

### PR DESCRIPTION
**Pull request by anarazel**
Only tested on the html output locally (with a regex), so this probably
doesn't *quite* work as-is.

The flag_imgs hash could now be a list, but I didn't know how to do that syntaxwise.

The resulting html could also be significantly reduced in size by just removing a few unnecessary newlines etc...

### CODE REVIEW

**Comment by anarazel** [comment]
For me this makes rendering go from > 4s to < 0.5s.

**Comment by mhagander** [comment]
Looks like this would also reduce the size of the resulting HTML by a non-trivial amount, which will also help with the rendering time (probably has less effect on the compressed size and thus the network traffic, but just the pure HTML parsing part is a win as well).

**Comment by anarazel** [comment]
FWIW, even if the rendering performance benefits down turn out to be not as large for others, just reducing the size of the status page output due to removing redundant data (alt, height, width) out-of-line seems like a good idea.

**Comment by adunstan** [comment]
See b463cd429d3e5

**Comment by anarazel** [comment]
Thanks!

It's nice how snappy the frontpage now feels. And a bit absurd that moving things around like this can have such an impact.

**Pull request closed without merging**
